baseURL = 'https://formingworlds.space/'
languageCode = 'en'
title = 'Forming Worlds'

# For GitHub Pages preview before custom domain
# baseURL = 'https://formingworlds.github.io/formingworlds-website/'

[params]
  googleAnalytics = 'G-SZP8X4X04B'
  description = 'The Forming Worlds team investigates the evolution of terrestrial worlds to understand how the origins of planets and life are interconnected.'
  institution = 'Kapteyn Astronomical Institute, University of Groningen'
  email = 'tim.lichtenberg@rug.nl'
  email2 = 'contact@formingworlds.space'
  github = 'https://github.com/FormingWorlds'
  bluesky = 'https://bsky.app/profile/timlichtenberg.bsky.social'
  scixplorer = 'https://scixplorer.org'
  proteus = 'https://proteus-framework.org'
  discord = 'https://discord.gg/formingworlds'

[params.formspree]
  formId = 'mqeykdbb'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 5
  [[menus.main]]
    name = 'Research'
    url = '/research/'
    weight = 10
  [[menus.main]]
    name = 'Team'
    url = '/team/'
    weight = 20
  [[menus.main]]
    name = 'Join'
    url = '/join/'
    weight = 40
  [[menus.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 50

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[sitemap]
  changefreq = 'weekly'
  priority = 0.6
  filename = 'sitemap.xml'

[build]
  [build.buildStats]
    enable = true
